server:
  port: 8081

oauth2:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true
    username: root
    password: 

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    initialization-mode: always
